console.log("Hello World");

var nome = "João"; // variável global;
let idade = 20; // variável local;
const altura = 1.75; // variável constante - não pode ser alterada;	

console.log(nome);
console.log(idade);
console.log(altura);
console.log("==============================================");
console.log(typeof nome);
console.log(typeof idade);
console.log(typeof altura);
console.log("==============================================");
console.log("===== CURIOSIDADES =====");
console.log("==============================================");
console.log("Curiosidade 1: ");
let curiosidade1 = idade + 10;
console.log("O valor da minha variável curiosidade1 recebendo o valor da minha variável idade + 10 é: "+curiosidade1+" e ela vai ser do tipo: "+typeof curiosidade1);
console.log("==============================================");
console.log("Curiosidade 2: ");
let curiosidade2 = idade + '2';
console.log("Agora o valor da minha variável curiosidade2 recebendo o valor de idade + '2' é: "+curiosidade2+" e ela vai ser do tipo: "+typeof curiosidade2);
console.log("==============================================");
console.log("Curiosidade 3: ");
let curiosidade3 = idade + true;
console.log("O valor da minha variável curiosidade3 recebendo o valor de idade + true é: "+curiosidade3+" e ela vai ser do tipo: "+typeof curiosidade3);
console.log("==============================================");
console.log("Curiosidade 4: ");
let curiosidade4 = idade + false;
console.log("O valor da minha variável curiosidade4 recebendo o valor de idade + false é: "+curiosidade4+" e ela vai ser do tipo: "+typeof curiosidade4);
console.log("==============================================");
console.log("Curiosidade 5: ");
let curiosidade5 = idade + null;
console.log("O valor da minha variável curiosidade5 recebendo o valor de idade + null é: "+curiosidade5+" e ela vai ser do tipo: "+typeof curiosidade5);
console.log("==============================================");
console.log("Curiosidade 6: ");
let curiosidade6 = '10' + idade;
console.log("O valor da minha variável curiosidade6 recebendo o valor de '10' + idade é: "+curiosidade6+" e ela vai ser do tipo: "+typeof curiosidade6);
console.log("==============================================");
console.log("Ou seja, se eu somar 'number' + 'number' o resultado será 'number', se eu somar 'string' + 'number' ou vice-versa o resultado será 'string' e não acontece a soma acontece a concatenação.");
console.log("Se eu somar 'number' + 'true'=1 eu vou ter number + 1, e o tipo será 'number'.");
console.log("Se eu somar 'number' + 'false'=0 eu vou ter number + 0, e o tipo será 'number'.");
console.log("==============================================");
let valorString1 = '10';
let valorString2 = '30';
let valorFinalString = valorString1 + valorString2;
console.log("Não tem soma, tem concatenação, então o resultado é: "+valorFinalString);
console.log(valorFinalString);
console.log("==============================================");